### ISSUE TITLE
[Feature Request] Add an option to the rename rom to datomatic match

### ISSUE THREAD

**Issue by casasfernando** [mroach/n64-go#10]
Just found this tool and it's really cool.

One option I'm missing, for example while running the validate command, is to rename the rom file to match the filename found in the dat file. This will help a lot while "normalizing" a rom library.
A more detailed description of the flow would be:

1. Validate the rom against the datfile
2. If a match is found check if the rename option is enabled
3. if the rename option is enabled check if the current rom filename matches the one from the datfile match.
4. If the filename doesn't match, rename the current rom file to match the one from the datfile.

e.g: rom64 validate --rename

Same option could be available for the convert command as well.

What do you think?

Thanks

**Comment by mroach** [comment]
Hi there! I'm happy someone is finding this tool to be useful :)
Thanks for getting in touch with a suggestion. I think the idea makes sense and I'm having a look at a clean way to do it. I need to review the datomatic file more to see if there can be duplicate names for hashes, and come up with a sensible way to deal with file naming conflicts. 
But like I say, the idea is a good one and I'll be looking into it!

**Comment by casasfernando** [comment]
The tool is not only useful, is brilliant. The perfect fit for a script to normalize a big rom collection.
I wish I can find the same for other systems, like NES, SNES, Megadrive/Genesis, etc.

Keep up with the good work.

**Comment by mroach** [comment]
I was working on a new more generic tool that is multi-platform. I decided to do that one in Rust as a learning project, so it was taking a long time. I might get back on it. I did have the basics of a couple platforms working though.

Give this version a try and see how you like it :) https://github.com/mroach/rom64/releases/tag/v0.5.4

**Comment by casasfernando** [comment]
Works like a charm!

BTW I will keep an eye on https://github.com/mroach/romboss. :)

Keep up with the  good work.
Thanks
